version: '3.8'
services:
  mysql:
    container_name: db-container
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test  
      MYSQL_ROOT_PASSWORD: password
    restart: always
    cap_add:
      - SYS_NICE

  redis:
    container_name: redis-container
    image: redis:latest
    command: --port 6380
    ports:
      - "6380:6380"
    volumes:
      - cache:/data
    restart: always

  crm-service:
    container_name: crm-container
    image: crm-image
    restart: unless-stopped
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - '8080:4000'
    # volumes:
      # - ./:/app
      # - /app/node_modules
      # - /app/dist
    environment:
      - PORT=4000
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=test
      - REDIS_HOST=redis
      - REDIS_PORT=6380
    env_file:
      - ./.env
    command: yarn start:prod
    depends_on:
      - mysql
      - redis

volumes: 
  db:
  cache:
