export enum Disposition {
  new = 'New',
  interested = 'Interested',
  notInterested = 'Not Interested',
  skip = 'Skip',
  answeringMachine = 'Answering Machine',
  callback = 'Callback',
  sale = 'Sale',
  busy = 'Busy',
  wrongNumber = 'Wrong Number',
  unreachable = 'Unreachable',
  dnc = 'DNC',
  sms = 'SMS',
  email = 'Email',
  link = 'Link',
}
